server:
  port: 9000

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

short-link:
#  默认域名
  domain:
    default: wgz.link:9000
#  允许跳转域名白名单
  goto-domain:
    white-list:
      enable: true
      names: 'github，知乎,掘金,gitee,知识星球'
      details:
        - github.com
        - zhihu.com
        - juejin.cn
        - gitee.com
        - wx.zsxq.com
#  高德地图 API key
  stats:
    locale:
      amap-key: 7093596fecdf29f5cc3f3dc6cfbbaabd